services:

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/elice/thief/ssl/nginx.conf:/etc/nginx/nginx.conf
      - /home/elice/thief/ssl/www:/var/www/certbot

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/elice/thief/ssl/letsencrypt:/etc/letsencrypt
      - /home/elice/thief/ssl/www:/var/www/certbot
      - /home/elice/thief/ssl/log:/var/log/letsencrypt
    command: "certonly --webroot --webroot-path=/var/www/certbot --email ${SSL_EMAIL} --agree-tos --no-eff-email -d ${SERVER_NAME}"